### PR TITLE
add Fears of Macros to the references

### PR DESCRIPTION
**Pull request by capfredf**
I think @greghendershott's guide on macros is awesome.

### CODE REVIEW

**Comment by greghendershott** [comment]
Thanks for saying so. However to the extent the bee is about syntax-PARSE, FoM isn't so awesome. It mainly says go read the docs.

Probably a better PR or issue would be one filed against FoM -- to make sure I have a link from FoM to additional resources like the syntax-parse example repo! :smile:

**Comment by greghendershott** [comment]
Oh, I just realized I already [added such a link a few years ago](https://github.com/greghendershott/fear-of-macros/commit/5e0910e68ec63791e6fec1bc836fe413ca30e64d).

**Comment by bennn** [comment]
Right --- the announcement doesn't talk about Fear of Macros because it doesn't talk about syntax parse.

I would be happy including a note along those lines, though. The Syntax Parse Examples [docs](https://docs.racket-lang.org/syntax-parse-example/index.html?q=syntax-parse-examples#%28part._.Tutorials%29) say this:
> The Fear of Macros tutorial is also very good, but was written before the age of syntax parse.
and we could include that, or something similar.

**Comment by greghendershott** [comment]
This might be nit-picky, but:

> The Fear of Macros tutorial is also very good, but was written before the age of syntax parse.

Actually the whole [last section](https://www.greghendershott.com/fear-of-macros/Robust_macros__syntax-parse.html) of Fear of Macros "builds a case" for why something like `syntax-parse` is good.

I just didn't go further into it because, as I wrote:

> November 1, 2012: So here’s the deal. After writing everything up to this point, I sat down to re-read the documentation for syntax-parse. It was...very understandable. I didn’t feel confused.
>
> Why? The documentation has a nice Introduction with many simple examples, followed by an Examples section illustrating many real-world scenarios.
>
> Update: Furthermore, Ben Greenman has created a package whose docs provide an excellent set of even more Syntax Parse Examples.

Regardless I 100% agree FoM isn't a resource for learning about how to use syntax-parse. :smile:

**Comment by bennn** [comment]
The nitpick is welcome. What to say instead?

> The Fear of Macros tutorial is a great resource for basic macro engineering (though, not syntax-parse in particular).

**Comment by greghendershott** [comment]
That would be wonderful. Thanks!

**Pull request closed without merging**
